<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325104933 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, document_type VARCHAR(50) NOT NULL, document_url VARCHAR(500) NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, submission_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D8698A76E1FD4933 ON document (submission_id)');
        $this->addSql('CREATE TABLE rental_contract (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date DATE NOT NULL, end_date DATE NOT NULL, monthly_payment NUMERIC(10, 2) NOT NULL, contract_status VARCHAR(20) NOT NULL, purchase_option_price NUMERIC(10, 2) DEFAULT NULL, last_payment_date DATE DEFAULT NULL, next_payment_due DATE DEFAULT NULL, payments_received INT NOT NULL, total_payments INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, submission_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D9E9316AE1FD4933 ON rental_contract (submission_id)');
        $this->addSql('CREATE TABLE submission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, profession VARCHAR(100) NOT NULL, monthly_income NUMERIC(10, 2) NOT NULL, duration INT DEFAULT NULL, annual_km INT DEFAULT NULL, monthly_total NUMERIC(10, 2) DEFAULT NULL, rejection_reason TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, client_id INT DEFAULT NULL, vehicle_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB055AF319EB6921 ON submission (client_id)');
        $this->addSql('CREATE INDEX IDX_DB055AF3545317D1 ON submission (vehicle_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_submission_client_vehicle_type ON submission (client_id, vehicle_id, type)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(50) NOT NULL, last_name VARCHAR(50) NOT NULL, phone VARCHAR(20) NOT NULL, address TEXT DEFAULT NULL, rgpd_consent BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_identifier_email ON "user" (email)');
        $this->addSql('CREATE TABLE vehicle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, brand VARCHAR(100) NOT NULL, model VARCHAR(100) NOT NULL, year INT NOT NULL, mileage INT NOT NULL, fuel_type VARCHAR(20) NOT NULL, color VARCHAR(50) DEFAULT NULL, sale_price NUMERIC(10, 2) DEFAULT NULL, rental_price_monthly NUMERIC(10, 2) DEFAULT NULL, availability_type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, description TEXT DEFAULT NULL, image_url VARCHAR(500) DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE document ADD CONSTRAINT FK_D8698A76E1FD4933 FOREIGN KEY (submission_id) REFERENCES submission (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rental_contract ADD CONSTRAINT FK_D9E9316AE1FD4933 FOREIGN KEY (submission_id) REFERENCES submission (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE submission ADD CONSTRAINT FK_DB055AF319EB6921 FOREIGN KEY (client_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE submission ADD CONSTRAINT FK_DB055AF3545317D1 FOREIGN KEY (vehicle_id) REFERENCES vehicle (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE document DROP CONSTRAINT FK_D8698A76E1FD4933');
        $this->addSql('ALTER TABLE rental_contract DROP CONSTRAINT FK_D9E9316AE1FD4933');
        $this->addSql('ALTER TABLE submission DROP CONSTRAINT FK_DB055AF319EB6921');
        $this->addSql('ALTER TABLE submission DROP CONSTRAINT FK_DB055AF3545317D1');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE rental_contract');
        $this->addSql('DROP TABLE submission');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE vehicle');
    }
}
