name: Deploy Backend to Heroku

on:
  push:
    branches: [master, main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "$HEROKU_API_KEY" | docker login registry.heroku.com --username=_ --password-stdin

      - name: Build image prod
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: docker build -f backend/deploy/Dockerfile -t registry.heroku.com/$HEROKU_APP_NAME/web ./backend

      - name: Push image
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          curl -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $HEROKU_API_KEY" \
            -d '{"updates": [{"type": "web", "docker_image": "'"$(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}})"'"}]}'
