name: Deploy Backend to Heroku

on:
  push:
    branches: [master, main]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-24.04
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Login Heroku Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      - name: Build image prod
        run: docker build -f backend/deploy/Dockerfile -t registry.heroku.com/$HEROKU_APP_NAME/web ./backend

      - name: Push image
        run: docker push registry.heroku.com/$HEROKU_APP_NAME/web

      - name: Release
        run: |
          curl -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation \
            -H "Content-Type: application/json" \
            -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
            -H "Authorization: Bearer $HEROKU_API_KEY" \
            -d '{"updates": [{"type": "web", "docker_image": "'"$(docker inspect registry.heroku.com/$HEROKU_APP_NAME/web --format={{.Id}})"'"}]}'
